module {
    public let css : Text = "
        :root{--ink:#1116a3;--outline:#000;--paper:#fff;--pink-neon:#ff00de;--green-neon:#00ff30;--pink:#ffd6f7;--green:#b3ffc1;--cyan:#b3fffc;--yellow:#f7ffb3;--orange:#ff7a00;--acid:#ebff00;--muted:#1116a3;--white:#fff;--font-body:'Providence Sans',sans-serif;--font-display:'Sketchbook Notes','Providence Sans',sans-serif;--radius-sm:10px;--radius-md:16px;--radius-lg:22px}
        *{box-sizing:border-box}html{min-width:320px;background:var(--paper)}body{min-height:100vh;margin:0;color:var(--ink);font-family:var(--font-body);background:var(--paper)}
        a{color:inherit}button,input,select{font:inherit}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:4px solid var(--pink-neon);outline-offset:4px}h1,h2,h3{color:var(--ink);font-family:var(--font-body);font-weight:700}
        .error-container{width:min(680px,calc(100% - 32px));margin:10vh auto;padding:clamp(26px,6vw,56px);border:4px solid var(--outline);border-radius:var(--radius-lg);background:var(--pink);box-shadow:9px 9px 0 var(--outline);text-align:left}.error-container h1,.error-title,.item-title{margin:0;font-family:var(--font-display);font-size:clamp(2.8rem,9vw,5.8rem);letter-spacing:-.025em;line-height:.8}.error-icon{display:inline-grid;place-items:center;margin-bottom:18px;padding:8px;border:3px solid var(--outline);border-radius:50%;background:var(--acid)}.error-message,.error-container p{font-size:1rem;font-weight:700;line-height:1.5}.back-button,.secondary-button{display:inline-flex;align-items:center;min-height:46px;margin:8px 8px 0 0;padding:10px 14px;border:3px solid var(--outline);border-radius:var(--radius-sm);background:var(--acid);box-shadow:5px 5px 0 var(--outline);font-weight:900;letter-spacing:.055em;text-decoration:none;text-transform:uppercase}.secondary-button{background:var(--white)}audio{width:100%;margin:24px 0;border:3px solid var(--outline);border-radius:var(--radius-sm)}
        @media(prefers-reduced-motion:reduce){*,*::before,*::after{transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}
    ";
};
